### ISSUE TITLE
how to get the host CPU usage

### ISSUE THREAD

**Issue by yang-wu** [luceracloud/tachyon-meter#1]
in the kstat.conf，only include:
cpu_stat:::user
cpu_stat:::idle
cpu_stat:::intr
cpu_stat:::iowait
cpu_stat:::syscall
cpu_stat:::kernel

but , cant not find the parameter about host CPU usage

**Comment by Licenser** [comment]
Do not open the same issue in multiple repositories this is deliberately wasting time.
